In [27]:
import numpy as np
import pandas as pd
import ast
# Import linear_kernel
from sklearn.metrics.pairwise import linear_kernel
#Import TfIdfVectorizer (scikit-learn)
from sklearn.feature_extraction.text import TfidfVectorizer

# Load data

In [80]:
# need to convert string representation of ingredients list to list using ast
#raw_recipes = pd.read_csv(data_path + "RAW_recipes.csv")
raw_recipes = pd.read_csv(data_path + "RAW_recipes.csv", converters={'ingredients': ast.literal_eval})
print("Total number of recipes: ", len(raw_recipes))
raw_recipes.head(5)

Total number of recipes:  231637


name      id  minutes  \
0  arriba   baked winter squash mexican style  137739       55   
1            a bit different  breakfast pizza   31490       30   
2                   all in the kitchen  chili  112140      130   
3                          alouette  potatoes   59389       45   
4          amish  tomato ketchup  for canning   44061      190   

   contributor_id   submitted  \
0           47892  2005-09-16   
1           26278  2002-06-17   
2          196586  2005-02-25   
3           68585  2003-04-14   
4           41706  2002-10-25   

                                                tags  \
0  ['60-minutes-or-less', 'time-to-make', 'course...   
1  ['30-minutes-or-less', 'time-to-make', 'course...   
2  ['time-to-make', 'course', 'preparation', 'mai...   
3  ['60-minutes-or-less', 'time-to-make', 'course...   
4  ['weeknight', 'time-to-make', 'course', 'main-...   

                                    nutrition  n_steps  \
0       [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
1   [173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]        9   
2  [269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]        6   
3   [368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]       11   
4   [352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]        5   

                                               steps  \
0  ['make a choice and proceed with recipe', 'dep...   
1  ['preheat oven to 425 degrees f', 'press dough...   
2  ['brown ground beef in large pot', 'add choppe...   
3  ['place potatoes in a large pot of lightly sal...   
4  ['mix all ingredients& boil for 2 1 / 2 hours ...   

                                         description  \
0  autumn is my favorite time of year to cook! th...   
1  this recipe calls for the crust to be prebaked...   
2  this modified version of 'mom's' chili was a h...   
3  this is a super easy, great tasting, make ahea...   
4  my dh's amish mother raised him on this recipe...   

                                         ingredients  n_ingredients  
0  [winter squash, mexican seasoning, mixed spice...              7  
1  [prepared pizza crust, sausage patty, eggs, mi...              6  
2  [ground beef, yellow onions, diced tomatoes, t...             13  
3  [spreadable cheese with garlic and herbs, new ...             11  
4  [tomato juice, apple cider vinegar, sugar, sal...              8

### reduce dataframe

In [81]:
selection = ["name", "id", "minutes", "ingredients"]
df = raw_recipes[selection].sample(100)
#df = raw_recipes[selection]

# CountVectorizer

## Basic example

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
data = df['ingredients']
data.head(3)

230086    [yukon gold potatoes, onion, mayonnaise, lemon...
130274    [maple syrup, cream cheese, crushed pineapple,...
152182    [peanut oil, extra firm tofu, scallion, orange...
Name: ingredients, dtype: object

In [53]:
vectorizer = CountVectorizer()

In [59]:
my_ingredients = ["sugar", "fruit", "rasperry", "pineapple", "brown sugar"]
vectorizer.fit(my_ingredients)
vectors = vectorizer.transform(my_ingredients).toarray()

In [60]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(vectors)
print(cos_sim)

[[1.         0.         0.         0.         0.70710678]
 [0.         1.         0.         0.         0.        ]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.70710678 0.         0.         0.         1.        ]]


## Database approach

### transorm lists in strings

In [82]:
#data['ingredients'] = data['ingredients'].apply(lambda x: ' '.join(map(str,x)))
#data
df['ingredients'] = [' '.join(x) for x in df['ingredients']]
df

name      id  minutes  \
137318              mocha mousse brownie trifle   58264       55   
76488                easy frozen chicken breast  265634       55   
105529                         hhhhhot crab dip   28140       40   
67720                         cuban shrimp stew   54232       63   
210846              thai spicy basil fried rice  473225       30   
...                                         ...     ...      ...   
47826                   chili s black bean soup   66087       55   
56689                         coleslaw dressing  435420       15   
117079            kerry simon  iron chef slider  383879       30   
154086  pasta with pink vodka sauce and sausage  327732       30   
100482    ground beef  rice and cabbage hot pot   15044      375   

                                              ingredients  
137318  brownies chocolate mousse mix whipped topping ...  
76488   chicken breasts barbecue sauce brown sugar hon...  
105529  philadelphia cream cheese crabmeat parmesan ch...  
67720   fresh lime juice garlic cloves oregano cumin s...  
210846  oyster sauce fish sauce soy sauce white sugar ...  
...                                                   ...  
47826   olive oil yellow onion carrot green bell peppe...  
56689   mayonnaise dijon mustard lime juice sugar vine...  
117079  ground beef dark beer bacon shiitake mushroom ...  
154086  spaghetti olive oil hot italian turkey sausage...  
100482  ground beef onion garlic chicken broth ketchup...  

[100 rows x 4 columns]

In [83]:
df.iloc[3]['ingredients']

'fresh lime juice garlic cloves oregano cumin shrimp salt and pepper olive oil onions red bell pepper green bell pepper yellow bell pepper celery fresh parsley cayenne pepper bay leaf tomato paste dry white wine water worcestershire sauce'

In [84]:
cv = CountVectorizer()

In [85]:
vectorized = cv.fit_transform(df['ingredients'])

In [86]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(vectorized)
print(cos_sim)

[[1.         0.         0.05423261 ... 0.         0.04583492 0.        ]
 [0.         1.         0.2981424  ... 0.05892557 0.06299408 0.13900961]
 [0.05423261 0.2981424  1.         ... 0.19764235 0.25354628 0.13987572]
 ...
 [0.         0.05892557 0.19764235 ... 1.         0.20044593 0.22116293]
 [0.04583492 0.06299408 0.25354628 ... 0.20044593 1.         0.15762208]
 [0.         0.13900961 0.13987572 ... 0.22116293 0.15762208 1.        ]]


In [87]:
cos_sim.shape

(100, 100)

In [88]:
# get reverse mapping of indices
indices = pd.Series(df.index, index=df['ingredients']).drop_duplicates()

# Fuzz approach