In [1]:
from sklearn.feature_extraction.text import CountVectorizer

# Count Vectorizer

In [2]:
vectorizer = CountVectorizer()

In [19]:
corpus = [
          'sugar, fruit, rasperry, pineapple',
          'onion tomato garlic pizza orange',
          'apple banana',
          'beer bread sausage fish',
]

In [20]:
# learn the vocabulary and store CountVectorizer sparse matrix in X
X = vectorizer.fit_transform(corpus)

In [22]:
# retrieving the matrix in the numpy form
X.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [23]:
# transforming a new document according to learn vocabulary
vectorizer.transform(['A new document.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
# transforming a new document according to learn vocabulary
vectorizer.transform(['sugar garlic rasperry pineapple']).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0]])

# SequenceMatcher

In [25]:
from difflib import SequenceMatcher

## Lists with permuted items

In [34]:
my_ingredients = ["sugar", "fruit", "rasperry"]
recipe = ["fruit", "rasperry", "sugar"]
SequenceMatcher(None, recipe, my_ingredients).ratio()

0.6666666666666666

## ...

In [32]:
my_ingredients = ["sugar", "fruit", "rasperry"]
recipe = ["sugar", "onion", "tomato", "pineapple"]
SequenceMatcher(None, recipe, my_ingredients).ratio()

0.2857142857142857

In [31]:
my_ingredients = ("sugar", "fruit", "rasperry")
recipe = ("sugar", "onion", "tomato", "pineapple")
SequenceMatcher(None, recipe, my_ingredients).ratio()

0.2857142857142857

In [30]:
my_ingredients = "sugar"
recipe = "sugar"
SequenceMatcher(None, recipe, my_ingredients).ratio()

1.0

# Word2Vec

In [18]:
#from gensim.models import word2vec

# Fuzz

## Compare two lists of strings

In [9]:
from thefuzz import fuzz
from thefuzz import process

In [10]:
my_ingredients = ["sugar", "fruit", "rasperry", "pineapple"]
recipe = ["sugar", "onion", "tomato", "pineapple"]

In [11]:
fuzz.ratio(my_ingredients, recipe)

76

### Lists of different lengths

In [12]:
my_ingredients = ["sugar", "fruit", "rasperry"]
recipe = ["sugar", "onion", "tomato", "pineapple"]

In [13]:
fuzz.ratio(my_ingredients, recipe)

62

### Lists with permutated item order

In [14]:
my_ingredients = ["onion", "sugar", "pineapple", "tomato"]
recipe = ["sugar", "onion", "tomato", "pineapple"]

In [15]:
fuzz.ratio(my_ingredients, recipe)

66

In [16]:
my_ingredients = ["onion", "sugar", "pineapple", "tomato"]
recipe = ["onion", "sugar", "pineapple", "tomato"]

In [17]:
fuzz.ratio(my_ingredients, recipe)

100